[workspace]
resolver = "2"
members = [
    "contracts/sep41-token",
]

[workspace.dependencies]
soroban-sdk = "22.0.1"
soroban-token-sdk = "22.0.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
